version: "3.8"

services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neoneoneo
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data

  data_loader:
    build:
      context: .
      dockerfile: DockerFile.yml
    volumes:
      - ./data_loader:/app

    depends_on:
      - mongo
      - cassandra
      - neo4j

volumes:
  mongo_data:
  cassandra_data:
  neo4j_data:

  