# Usamos un python 3.10 como base
FROM python:3.10

# Nuestro directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el contenido del directorio actual en el directorio de trabajo del contenedor
COPY . /app

# Instala los paquetes de python que se encuentran en el archivo requirements.txt
COPY requirements.txt .
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Corre el app.py cuando se inicie el contenedor y pasen 75 segundos para que se preparen las bases de datos
CMD ["sh", "-c", "sleep 75 && python3 app.py"]
